name: Create unsigned Release and Debug artifact on tag

on:
  push:
    tags:
      - '*'

jobs:
  Build_release_artifact:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Write run number to properties
        run: echo ciBuildNumber=${{ github.run_number }} > ./local.properties

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/parameters
          mode: normalParameters

      - name: Build release apk
        run: ./gradlew clean assemble

      - name: Rename built artifact
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}.apk

      - name: Export release apk
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/release/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move artifacts to proper dir
        run: |
          mkdir app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}
          mv app/build/outputs/ app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}

      - name: Create archive
        run: tar -czvf app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}.tar.gz app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}

      - name: Export release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}
          path: app/build/${{ env.ARTIFACT_RELEASE_NAME }}_${{ github.run_number }}

  Build_debug_artifact:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Write run number to properties
        run: echo ciBuildNumber=${{ github.run_number }} > ./local.properties

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/parameters
          mode: normalParameters

      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Rename built artifact
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}.apk

      - name: Export debug apk
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/debug/${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move artifacts to proper dir
        run: |
          mkdir app/build/${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}
          mv app/build/outputs/ app/build/${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}

      - name: Create archive
        run: tar -czvf app/build/${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}.tar.gz app/build/${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}

      - name: Export debug artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}
          path: app/build/${{ env.ARTIFACT_DEBUG_NAME }}_${{ github.run_number }}